INSERT INTO ROLES (name, description, creation_date)
values ('ADMIN', 'Administrator Role', NOW()),
       ('USER', 'User Role', NOW());

INSERT INTO ORGANIZATIONS (name, image, address, phone, email, welcome_text, about_us_text, creation_date)
values ('Somos Mas', 'somos-mas.jpg', 'Direccion n', 1212323, 'somosmas@gmail.com', 'Welcome to Somos Mas',
        'Somos una organizacion', NOW()),
       ('Unicef', 'unicef.jpg', 'Direccion u', 1212321, 'unicef@gmail.com', 'Welcome to Unicef',
        'Somos una organizacion', NOW());

INSERT INTO ACTIVITIES (name, content, image, deleted, creation_date)
values ('Actividades deportivas', 'Deporte para los niños', 'img.jpg', false, NOW()),
       ('Colecta de alimentos', 'Colecta de ropa', 'img.jpg', false, NOW());

INSERT INTO USERS (first_name, last_name, email, password, photo, role_id, deleted, creation_date)
values ('User1', 'User1', 'user1@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user1.jpg', (SELECT id FROM ROLES WHERE name = 'USER'), false, NOW()),
       ('User2', 'User2', 'user2@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user2.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User3', 'User3', 'user3@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user3.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User4', 'User4', 'user4@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user4.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User5', 'User5', 'user5@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user5.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User6', 'User6', 'user6@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user6.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User7', 'User7', 'user7@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user7.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User8', 'User8', 'user8@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user8.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User9', 'User9', 'user9@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user9.jpg', (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('User10', 'User10', 'user10@gmail.com', '$2a$10$McgCwPpuDJ/8yE20V5GaeOGC45FVk.e70G2fmwr/KAZafw.gxhBYC',
        'user10.jpg',
        (SELECT id FROM ROLES WHERE name = 'USER'),
        false, NOW()),
       ('Admin1', 'Admin1', 'admin1@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin1.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin2', 'Admin2', 'admin2@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin2.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin3', 'Admin3', 'admin3@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin3.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin4', 'Admin4', 'admin4@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin4.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin5', 'Admin5', 'admin5@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin5.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin6', 'Admin6', 'admin6@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin6.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin7', 'Admin7', 'admin7@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin7.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin8', 'Admin8', 'admin8@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin8.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin9', 'Admin9', 'admin9@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin9.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW()),
       ('Admin10', 'Admin10', 'admin10@gmail.com', '$2a$10$YL1/O8eLEYrQy.5H1Rc2dO7umIhK3wKPdQoZWembDWFdgDOmcSZB6',
        'admin10.jpg',
        (SELECT id FROM ROLES WHERE name = 'ADMIN'),
        false, NOW());
